# Generated by Django 3.1.2 on 2020-12-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='recovery_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
