# Generated by Django 3.1.2 on 2020-12-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recovery_recovery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='About_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='About_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
