# Generated by Django 3.1.2 on 2020-12-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201221_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_action',
            name='action',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.about'),
        ),
    ]
