# Generated by Django 3.1.2 on 2020-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201221_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_action',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
