# Generated by Django 3.1.2 on 2020-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_about_action_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='blog_right_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='blog_right_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='information',
            name='service_right_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='service_right_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
