# Generated by Django 3.1.2 on 2020-12-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_blog_qoute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='need_recovery_text',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='request_text',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
