# Generated by Django 3.1.2 on 2020-12-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201223_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_qoute',
            new_name='BlogQoute',
        ),
    ]
