# Generated by Django 3.1.2 on 2020-12-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201223_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author_email',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
