# Generated by Django 3.1.2 on 2020-12-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201224_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='author_last_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='author_name',
        ),
    ]
