# Generated by Django 3.1.2 on 2020-12-24 04:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201224_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
