# Generated by Django 3.1.2 on 2020-12-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_blogcomment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='blog',
        ),
    ]
