# Generated by Django 3.1.2 on 2020-12-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_blogcomment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('status', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('mini_title', models.CharField(blank=True, max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('quality1', models.CharField(blank=True, max_length=300)),
                ('quality2', models.CharField(blank=True, max_length=300)),
                ('quality3', models.CharField(blank=True, max_length=300)),
                ('quality4', models.CharField(blank=True, max_length=300)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
