# Generated by Django 3.1.2 on 2020-12-28 08:00

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201224_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('info', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('country', models.CharField(blank=True, max_length=300)),
                ('bin', models.IntegerField(blank=True, default=0)),
                ('weekday1', models.CharField(blank=True, max_length=300)),
                ('weekday2', models.CharField(blank=True, max_length=300)),
                ('time1', models.TimeField(blank=True)),
                ('time2', models.TimeField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, max_length=300)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('rating', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=300)),
                ('last_name', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, default='', max_length=300)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('message', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
