# Generated by Django 3.1.2 on 2020-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201228_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, default='', max_length=300)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('date', models.DateTimeField(blank=True)),
                ('comment_id', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, default='', upload_to='upload')),
            ],
        ),
    ]
