# Generated by Django 3.1.5 on 2021-01-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='summ',
            field=models.IntegerField(default=0),
        ),
    ]
