# Generated by Django 3.1.5 on 2021-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_cartitem_summ'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cart',
            name='country',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cart',
            name='fn',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cart',
            name='ln',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='cart',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
